stages:
  prepare:
    cmd: python prepare.py
    deps:
      - data/customers-100000.txt
      - prepare.py
    outs:
      - data/prepared_data.csv

  train:
    cmd: python train.py
    deps:
      - data/prepared_data.csv
      - train.py
    outs:
      - model.joblib

  validate:
    cmd: python validate.py
    deps:
      - data/test_data.csv
      - data/model.joblib
      - validate.py

  deploy:
    cmd: python deploy.py
    deps:
      - data/model.joblib
      - deploy.py
