stages:
  prepare:
    cmd: python3 prepare.py
    deps:
      - data/customers-100000.txt
      - prepare.py
    outs:
      - data/prepared_data.csv

  train:
    cmd: python3 train.py
    deps:
      - data/prepared_data.csv
      - train.py
    outs:
      - data/model.joblib

  validate:
    cmd: python3 validate.py
    deps:
      - data/test_data.csv
      - data/model.joblib
      - validate.py

  deploy:
    cmd: python3 deploy.py
    deps:
      - data/model.joblib
      - deploy.py
